# Generated by Django 5.0.4 on 2024-08-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentIS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='start_date',
            field=models.CharField(max_length=8),
        ),
    ]
