# Generated by Django 5.0.7 on 2024-07-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentIS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sex',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Non-Binary', 'Non-Binary'), ('Other', 'Other')], max_length=15, null=True),
        ),
    ]
